const LOGIN = 'LOGIN';
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

const SIGNUP = 'SIGNUP';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

const TOKEN_CREATED = 'TOKEN_CREATED';


export {
  LOGIN,
  LOGIN_REQUEST,
  LOGIN_FAILURE,
  LOGIN_SUCCESS,
  SIGNUP,
  SIGNUP_REQUEST,
  SIGNUP_FAILURE,
  SIGNUP_SUCCESS,
  TOKEN_CREATED
};
